=== DavidBadura/xsd-builder/example/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="library">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="books">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="book" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="isbn" type="xs:string"/>
                    <xs:element name="title" type="xs:string"/>
                    <xs:element name="author" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="identifier" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:key name="book-id">
            <xs:selector xpath="book"/>
            <xs:field xpath="@identifier"/>
          </xs:key>
          <xs:keyref name="author-ref" refer="book-id">
            <xs:selector xpath="book"/>
            <xs:field xpath="author"/>
          </xs:keyref>
        </xs:element>
        <xs:element name="authors">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="author" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                  </xs:sequence>
                  <xs:attribute name="identifier" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:key name="author-id">
            <xs:selector xpath="author"/>
            <xs:field xpath="@identifier"/>
          </xs:key>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== DavidBadura/xsd-builder/example/library.xml
<?xml version="1.0" encoding="UTF-8"?>

<library
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="library.xsd">



    <books>
        <book identifier="sina">
            <isbn></isbn>
            <title></title>
            <author>sina</author>
        </book>
        <book identifier="foo">
            <isbn></isbn>
            <title></title>
            <author>a</author>
        </book>
    </books>

    <authors>
        <author identifier="sina">
            <name>Sina</name>
        </author>

        <author identifier="foo">
            <name>Sina</name>
        </author>
    </authors>

</library>
